# Generated by Google Gemini
import hashlib
import string
import multiprocessing
import sys

# --- CONFIGURATION ---
TARGET_HASH = "1e85a6"  # Replace with the hash from the server
ALGO = "md5"            # Change to "sha1" or "sha256" if needed
CHARS = string.ascii_letters + string.digits
# ---------------------

def solver(start_char, target, result_queue):
    """Search for a collision starting with a specific character."""
    for length in range(1, 8):
        # We fix the first character to distribute work across cores
        import itertools
        for suffix in itertools.product(CHARS, repeat=length-1):
            candidate = start_char + ''.join(suffix)
            
            # Compute hash
            h = hashlib.new(ALGO)
            h.update(candidate.encode())
            cur_hash = h.hexdigest()
            
            if cur_hash.startswith(target):
                result_queue.put(candidate)
                return

if __name__ == "__main__":
    print(f"[*] Target: {TARGET_HASH} | Algorithm: {ALGO}")
    print(f"[*] Spawning processes for {len(CHARS)} starting points...")

    result_queue = multiprocessing.Queue()
    processes = []

    # Create a process for each possible starting character
    for c in CHARS:
        p = multiprocessing.Process(target=solver, args=(c, TARGET_HASH, result_queue))
        p.start()
        processes.append(p)

    # Wait for any process to put a result in the queue
    try:
        solution = result_queue.get(timeout=25) # Stay under the 30s limit
        print(f"\n[+] COLLISION FOUND: {solution}")
        
        # Clean up: Kill other processes
        for p in processes:
            p.terminate()
            
    except:
        print("\n[!] Timed out or failed to find collision.")
        for p in processes:
            p.terminate()